# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-14 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20170114_1913'),
        ('base', '0023_auto_20170114_1954'),
    ]

    operations = [
    ]
