# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('price', models.FloatField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_site.Menu')),
            ],
        ),
    ]
