# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_site', '0002_menuprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuprice',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
