# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 22:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20170118_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='bussines',
            new_name='business',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 18, 22, 26, 3, 115095)),
        ),
    ]
