# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 20:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20170112_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='factor',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 12, 20, 29, 44, 375903)),
        ),
    ]
