# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-12 17:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20170112_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 12, 17, 1, 32, 174631)),
        ),
    ]
