# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-31 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(null=True, upload_to='photos')),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField(default='twitter.com', null=True)),
                ('instagram', models.URLField(default='instagram.com', null=True)),
                ('facebookpage', models.URLField(default='facebook.com', null=True)),
                ('yelp', models.URLField(default='yelp.com', null=True)),
                ('gplus', models.URLField(default='gplus.com', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('image', models.FileField(upload_to='photos')),
                ('comments', models.TextField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_site.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='photos')),
                ('asbackground', models.BooleanField(default=False)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_site.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='StaffServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('image', models.FileField(upload_to='photos')),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='WebDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.IntegerField(default=1)),
                ('business', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.Business')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business_site.Website')),
            ],
        ),
        migrations.AddField(
            model_name='webdomain',
            name='website',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='business_site.Website'),
        ),
        migrations.AddField(
            model_name='staffservices',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_site.Website'),
        ),
        migrations.AddField(
            model_name='links',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business_site.Website'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business_site.Website'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business_site.Website'),
        ),
        migrations.AddField(
            model_name='category',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_site.Website'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='website',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='business_site.Website'),
        ),
    ]
