# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-14 20:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20170114_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.N_Prefix'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suffix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.N_Suffix'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 14, 20, 27, 38, 714224)),
        ),
        migrations.AlterField(
            model_name='service',
            name='tarifa_horaria',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
