# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-31 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2016, 12, 31, 11, 23, 36, 800734)),
        ),
    ]
