# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-14 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('base', '0025_auto_20170114_1152'),
        ('base', '0026_auto_20170114_2051'),
    ]

    operations = [
    ]
