# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-14 19:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20170114_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='prefix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.N_Prefix'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suffix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.N_Suffix'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 14, 19, 13, 26, 935315)),
        ),
    ]
