# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-11 20:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20170110_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='N_Event_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='widget_sk',
            field=models.CharField(default=123456789, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 11, 20, 21, 12, 181536)),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.N_Event_Status'),
            preserve_default=False,
        ),
    ]
