# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-14 04:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='bussines',
            new_name='business',
        ),
        migrations.RemoveField(
            model_name='address',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 14, 4, 21, 28, 931817)),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set([('description', 'business')]),
        ),
    ]
