# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-13 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='n_city',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.N_State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 13, 18, 56, 58, 45493)),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='cant',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.DeleteModel(
            name='N_City',
        ),
    ]
