# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-18 04:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Address'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 18, 4, 17, 46, 839917)),
        ),
    ]
