# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20170116_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 16, 20, 25, 52, 455121)),
        ),
    ]
