# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 20:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measure',
            old_name='magnitudes.json',
            new_name='magnitude',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='bussines',
            new_name='business',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 16, 20, 24, 8, 940320)),
        ),
    ]
