# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20170112_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Business')),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 13, 19, 36, 27, 722066)),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='cant',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.Category'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('name', 'recipe', 'business')]),
        ),
    ]
