# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-14 19:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20170113_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 14, 19, 50, 24, 258540)),
        ),
        migrations.AlterField(
            model_name='service',
            name='tarifa_horaria',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set([('description', 'business')]),
        ),
    ]
