# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-18 16:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20170118_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 18, 16, 39, 32, 209059)),
        ),
    ]
