# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 21:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20170111_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_goal', models.IntegerField(default=0)),
                ('factor', models.DecimalField(decimal_places=2, max_digits=100000000)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Measure')),
            ],
        ),
        migrations.CreateModel(
            name='Magnitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ingredients',
            name='business',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.Business'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='business',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.Business'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 11, 21, 38, 7, 510960)),
        ),
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.Business'),
        ),
        migrations.AddField(
            model_name='measure',
            name='magnitudes.json',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.Magnitude'),
        ),
    ]
