# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-14 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20170113_2034'),
        ('base', '0019_auto_20170113_1857'),
    ]

    operations = [
    ]
