# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-18 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20170116_2025'),
        ('base', '0025_merge'),
    ]

    operations = [
    ]
