# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-13 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20170113_1609'),
        ('base', '0017_auto_20170112_2029'),
    ]

    operations = [
    ]
