# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-03 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_site', '0003_auto_20170102_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.AlterField(
            model_name='website',
            name='business',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='website', to='base.Business'),
        ),
    ]
