# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-11 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20170111_2021'),
        ('base', '0010_auto_20170111_2138'),
    ]

    operations = [
    ]
