# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='bussines',
            new_name='business',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 13, 20, 50, 0, 843917)),
        ),
    ]
