# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 20:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20170113_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='bussines',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.Business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='bussines',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.Business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 13, 20, 33, 57, 22932)),
        ),
    ]
