# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20170105_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 10, 9, 25, 22, 201096)),
        ),
    ]
