# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-05 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_cater', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='due',
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='current',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
